/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.io.Reader;
import java.io.StringReader;
import jflex.Lexer;

/**
 *
 * @author CIROSS
 */
public class ContadorPorVocales extends javax.swing.JFrame {

    Lexer lexer;
    
    public ContadorPorVocales() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanelGeneral = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaInput = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanelOutput = new javax.swing.JPanel();
        jPanelPalabras = new javax.swing.JPanel();
        jLabelVocal1 = new javax.swing.JLabel();
        jLabelResultVocal1 = new javax.swing.JLabel();
        jLabelVocal2 = new javax.swing.JLabel();
        jLabelResultVocal2 = new javax.swing.JLabel();
        jLabelVocal3 = new javax.swing.JLabel();
        jLabelResultVocal3 = new javax.swing.JLabel();
        jLabelVocal4 = new javax.swing.JLabel();
        jLabelResultVocal4 = new javax.swing.JLabel();
        jLabelVocal5 = new javax.swing.JLabel();
        jLabelResultVocal5 = new javax.swing.JLabel();
        jPanelEnteros = new javax.swing.JPanel();
        jButtonStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelGeneral.setOpaque(false);
        jPanelGeneral.setLayout(new java.awt.GridLayout(1, 0));

        jTextAreaInput.setColumns(20);
        jTextAreaInput.setLineWrap(true);
        jTextAreaInput.setRows(5);
        jScrollPane2.setViewportView(jTextAreaInput);

        jPanelGeneral.add(jScrollPane2);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanelOutput.setOpaque(false);
        jPanelOutput.setLayout(new java.awt.GridLayout(2, 2));

        jPanelPalabras.setOpaque(false);
        jPanelPalabras.setLayout(new java.awt.GridLayout(5, 0));

        jLabelVocal1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelVocal1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVocal1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelVocal1.setText("Palabras con 1 vocal:      ");
        jPanelPalabras.add(jLabelVocal1);

        jLabelResultVocal1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelResultVocal1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanelPalabras.add(jLabelResultVocal1);

        jLabelVocal2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelVocal2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVocal2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelVocal2.setText("Palabras con 2 vocales:  ");
        jPanelPalabras.add(jLabelVocal2);

        jLabelResultVocal2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelResultVocal2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanelPalabras.add(jLabelResultVocal2);

        jLabelVocal3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelVocal3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVocal3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelVocal3.setText("Palabras con 3 vocales:  ");
        jPanelPalabras.add(jLabelVocal3);

        jLabelResultVocal3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelResultVocal3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanelPalabras.add(jLabelResultVocal3);

        jLabelVocal4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelVocal4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVocal4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelVocal4.setText("Palabras con 4 vocales:  ");
        jPanelPalabras.add(jLabelVocal4);

        jLabelResultVocal4.setBackground(new java.awt.Color(255, 255, 255));
        jLabelResultVocal4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanelPalabras.add(jLabelResultVocal4);

        jLabelVocal5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelVocal5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVocal5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelVocal5.setText("Palabras con 5 vocales:  ");
        jPanelPalabras.add(jLabelVocal5);

        jLabelResultVocal5.setBackground(new java.awt.Color(255, 255, 255));
        jLabelResultVocal5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanelPalabras.add(jLabelResultVocal5);

        jPanelOutput.add(jPanelPalabras);

        jPanelEnteros.setOpaque(false);

        javax.swing.GroupLayout jPanelEnterosLayout = new javax.swing.GroupLayout(jPanelEnteros);
        jPanelEnteros.setLayout(jPanelEnterosLayout);
        jPanelEnterosLayout.setHorizontalGroup(
            jPanelEnterosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanelEnterosLayout.setVerticalGroup(
            jPanelEnterosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );

        jPanelOutput.add(jPanelEnteros);

        jPanel1.add(jPanelOutput);

        jButtonStart.setText("INICIAR CONTEO DE VOCALES");
        jButtonStart.setAlignmentX(0.5F);
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonStart);

        jPanelGeneral.add(jPanel1);

        jDesktopPane1.setLayer(jPanelGeneral, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        
        Reader reader = new StringReader(jTextAreaInput.getText() + " ");
        lexer = new Lexer(reader);
        
        try {
            System.out.println("entró al try");
            int output = lexer.yylex();
            System.out.println("entró al try siguiente linea");
            while (output != Lexer.YYEOF) {
                System.out.println("entró al while");
                lexer.yylex();
            }
            
            jLabelResultVocal1.setText(lexer.getContPalabras(0)+" palabras.");
            jLabelResultVocal2.setText(lexer.getContPalabras(1)+" palabras.");
            jLabelResultVocal3.setText(lexer.getContPalabras(2)+" palabras.");
            jLabelResultVocal4.setText(lexer.getContPalabras(3)+" palabras.");
            jLabelResultVocal5.setText(lexer.getContPalabras(4)+" palabras.");
            
        } catch (Exception e) {
            System.out.println("Atrape un error y lo maneje de forma correcta");
        }
    }//GEN-LAST:event_jButtonStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContadorPorVocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContadorPorVocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContadorPorVocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContadorPorVocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContadorPorVocales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStart;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelResultVocal1;
    private javax.swing.JLabel jLabelResultVocal2;
    private javax.swing.JLabel jLabelResultVocal3;
    private javax.swing.JLabel jLabelResultVocal4;
    private javax.swing.JLabel jLabelResultVocal5;
    private javax.swing.JLabel jLabelVocal1;
    private javax.swing.JLabel jLabelVocal2;
    private javax.swing.JLabel jLabelVocal3;
    private javax.swing.JLabel jLabelVocal4;
    private javax.swing.JLabel jLabelVocal5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelEnteros;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JPanel jPanelOutput;
    private javax.swing.JPanel jPanelPalabras;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaInput;
    // End of variables declaration//GEN-END:variables
}
